### ISSUE TITLE
Readme unclear on server-side install

### ISSUE THREAD

**Issue by bennydiamond** [MSchmoecker/No-Chest-Block#1]
`All player need to install this mod, it is not needed at a server`

I am confused by this statement. I don't know if the mod should be either installed exclusively on the server instance or rather on each clients connecting to a server.

Which of the following statement is true?

1- If mod is installed on server instance, connecting players do NOT need to install the mod on their local copy of Valheim.

2- All players connecting to a server need to have the mod installed on their local copy of Valheim. Server instance should NOT have the mod installed.

**Comment by MSchmoecker** [comment]
3 - All players connecting to a server need to have the mod installed on their local copy of Valheim. A dedicated server can have the mod installed but it will not do anything
