### ISSUE TITLE
Mod broken as of 0.219.16

### ISSUE THREAD

**Issue by marckskl** [MSchmoecker/No-Chest-Block#12]
I am getting the error attached in the log, while trying to open chests on the new Valheim update 0.219.16. 
[LogOutput.log](https://github.com/user-attachments/files/17823163/LogOutput.log)

**Comment by MSchmoecker** [comment]
You have a different mod that throws this error
```
[Error  : Unity Log] MissingFieldException: Field not found: int .InventoryGui.m_craftCookingBonusAmount Due to: Could not find field in class
Stack trace:
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Awake>(InventoryGui)
UnityEngine.GameObject:SetActive(GameObject, Boolean)
SetActiveOnAwake:Awake()
```

This means the inventory UI cannot be initialized properly and not all MUI patches are applied. MUC itself works.

Find the mod that causes this error, e.g. by disabling half of your mod list and starting the game. Repeat with the half that causes the error until you are down to the minimum amount of mods
