### ISSUE TITLE
Request to add compatibility patch for "Quick Stack - Store - Sort - Trash - Restock" (which I am the author of)

### ISSUE THREAD

**Issue by Goldenrevolver** [MSchmoecker/No-Chest-Block#4]
Hello, I'm the author of "Quick Stack - Store - Sort - Trash - Restock" which is getting popular enough that I'm getting reports of lost items when using with Multi User Chest. Of course, this is a user error, since your mod states that quick stacking mods are not compatible until you patch them, and I tell my users to stop using multiple mods that affect chests, because we all know how fragile valheims multiplayer chest system is.

I saw that you added a patch for the original Quick Stack, and would like to request one for my mod. I can take a look at the nature of your patch and maybe add a PR for one for my mod, but I would prefer if you were to check out my source code too. most of what you need should be in "QuickStackRestockModule.cs", especially the method ApplyToMultipleContainers which I use for both quick stacking and restocking. I can change the signature of it (since it's a bit dumb right now due to trophy priority sorting) if that makes it easier

My mod also has sorting and 'store all', so if those are also affected let me know

thank you for considering it

**Comment by MSchmoecker** [comment]
To also reply here: thanks for contacting me, on a compatibility patch is being worked. No ETA at this time

**Comment by MSchmoecker** [comment]
Done in MUC 0.4.0 and QSSTRS 1.3.1
