### ISSUE TITLE
Conflict with Backpacks

### ISSUE THREAD

**Issue by Oosquai** [MSchmoecker/No-Chest-Block#9]
Hi MSchmoecker!  I'm loving MultiUserChest and ItemHopper!  Thank you!

I'm finding a conflict with blaxxun's Backpacks mod.  With only MUC and Backpacks installed, if I put a stack of anything in a Backpack, split the stack, and then try to drop what's on my cursor onto the ground, I get a bunch of red error text in the console that calls out MUC.

Are you able to help please?

Thanks!

`[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace: MultiUserChest.Patches.InventoryGuiPatch.InventoryGuiOnDropOutsidePatch (InventoryGui __instance) (at <001e9b9d8ed84ff79636a2ae647de0e9>:0) (wrapper dynamic-method) InventoryGui.DMD(InventoryGui) UnityEngine.Events.InvokableCall.Invoke () (at <50b18efe22344b9eb3b7d77b08ea287f>:0) UnityEngine.Events.UnityEvent.Invoke () (at <50b18efe22344b9eb3b7d77b08ea287f>:0) UnityEngine.UI.Button.Press () (at <042da27c9af642978a8a5138113c4eed>:0) UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <042da27c9af642978a8a5138113c4eed>:0) UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <042da27c9af642978a8a5138113c4eed>:0) UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <042da27c9af642978a8a5138113c4eed>:0) UnityEngine.EventSystems.EventSystem:Update()`

**Comment by MSchmoecker** [comment]
Thanks for the report, will be fixed in the next release.

**Comment by Oosquai** [comment]
You rock!  Thank you so much!

**Comment by MSchmoecker** [comment]
Fixed in 0.5.6
